geoffreybauduin/yaorm

filterapply_test.go, yaormfilter/datefilter.go, yaormfilter/int64filter.go, yaormfilter/nilfilter.go, yaormfilter/stringfilter.go, yaormfilter/tools.go, yaormfilter/tools_test.go, yaormfilter/valuefilter.go
=> Adding lt/lte/gt/gte filters

model.go, model_test.go, requestbuilder.go
=> Adding yaorm.GenericCount function to count

db_test.go, dbprovider.go, executorhook.go, filterapply_test.go, model.go, model_test.go, sqlexecutor.go, testdata/database.go, testdata/executor.go
=> Passing context to ExecutorHook objects

_vendor/github.com/satori/go.uuid/LICENSE, _vendor/github.com/satori/go.uuid/README.md, _vendor/github.com/satori/go.uuid/uuid.go, _vendor/vendor.json, dbprovider.go
=> Adding UUID function on DBProvider instance

model_test.go, testdata/post.go
=> Adding example for recursive model subqueryloading

_vendor/github.com/loopfz/gadgeto/zesty/utils/rekordo/database.go, _vendor/github.com/loopfz/gadgeto/zesty/utils/rekordo/register.go, databasecapacity.go, dbprovider.go, filterapply.go, requestbuilder.go, table.go, table_test.go
=> Handling schemas for mysql/postgres

databasecapacity.go
=> Adding 'uuid' capacity

model_test.go, requestbuilder.go, testdata/2i.go
=> Handle table names starting by numbers

db_test.go, dbprovider.go, executorhook.go, executorhook_test.go, model_test.go, requestbuilder.go, sqlexecutor.go, table.go, testdata/executor.go
=> Logging insert/update/delete

db.go, db_test.go, dbprovider.go, dbprovider_test.go, requestbuilder.go, sqlexecutor.go
=> fix(): transactions were not really working

filterapply.go, filterapply_test.go, testdata/category.go, yaormfilter/filter.go
=> Handling limit / offset

_vendor/github.com/loopfz/gadgeto/zesty/utils/rekordo/database.go, db.go
=> connection max lifetime support

.travis.yml
=> Support for go1.10 / go1.11

README.md, filterapply_test.go, model.go, model_test.go, requestbuilder.go, requestbuilder_test.go, yaormfilter/filter.go
New yaormfilter.Filter methods:
- LoadColumns(columns ...string)
- GetLoadColumns() []string
- DontLoadColumns(columns ...string)
- GetDontLoadColumns() []string
=> Add ability to load only certain columns

model.go, model_test.go
=> feat(delete): allow deletion of models

executorhook.go, sqlexecutor.go, sqlexecutor_test.go
=> feat: provide logging hook for SqlExecutor.Exec

db.go, dbprovider.go, dbprovider_test.go, dbspecific.go, dbspecific_postgres.go, testdata/database.go
=> feat: introducing pg specifics -- set intervalstyle

.travis.yml, filterapply_test.go, go.sum, yaormfilter/boolfilter.go, yaormfilter/datefilter.go, yaormfilter/int64filter.go, yaormfilter/nilfilter.go, yaormfilter/stringfilter.go, yaormfilter/stringfilter_test.go, yaormfilter/tools.go, yaormfilter/valuefilter.go
=> feat: added raw filter

filterapply_test.go, yaormfilter/tools_test.go, yaormfilter/valuefilter.go
=> fix: bring back ValueFilter.IsEquality and ValueFilter.GetEquality

filterapply.go, model_test.go, testdata/post.go
Aka `.AddOption(yaormfilter.RequestOptions.LeftJoin)`
=> fix(leftjoin): make option working

_vendor/github.com/loopfz/gadgeto/zesty/utils/rekordo/database.go, db.go
=> feat(connections): can now configure max idle time of SQL connections
